"""add is_locked to user

Revision ID: 4f2c45d8fa6d
Revises: dbc8e5bd040c
Create Date: 2025-06-10 12:25:21.469530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2c45d8fa6d'
down_revision: Union[str, None] = 'dbc8e5bd040c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_locked')
    # ### end Alembic commands ###
