"""CASCADE property_image

Revision ID: 696b1c91ed32
Revises: b4325ee8ef2a
Create Date: 2025-06-08 07:37:42.429402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696b1c91ed32'
down_revision: Union[str, None] = 'b4325ee8ef2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_image_property_id_fkey', 'property_image', type_='foreignkey')
    op.create_foreign_key(None, 'property_image', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_image', type_='foreignkey')
    op.create_foreign_key('property_image_property_id_fkey', 'property_image', 'property', ['property_id'], ['property_id'])
    # ### end Alembic commands ###
