"""update wallet

Revision ID: 8a1ee02dd06e
Revises: 4f2c45d8fa6d
Create Date: 2025-06-10 16:08:31.439354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1ee02dd06e'
down_revision: Union[str, None] = '4f2c45d8fa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wallet', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    # ### end Alembic commands ###
