"""delete is_primary in PropertyImage

Revision ID: a11003b8f017
Revises: 9c4464f16c20
Create Date: 2025-05-31 13:56:39.510511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11003b8f017'
down_revision: Union[str, None] = '9c4464f16c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_image', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_image', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
