"""change posts

Revision ID: ade0453ad0e9
Revises: 7743ca8a170c
Create Date: 2025-06-11 17:52:23.368903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade0453ad0e9'
down_revision: Union[str, None] = '7743ca8a170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('posts', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
