"""add is_read to Notifications

Revision ID: b4325ee8ef2a
Revises: 41fbb9f737f9
Create Date: 2025-06-07 14:43:32.651401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4325ee8ef2a'
down_revision: Union[str, None] = '41fbb9f737f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_read', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'is_read')
    # ### end Alembic commands ###
