"""Check changes

Revision ID: d52bdf21581d
Revises: 
Create Date: 2025-04-25 09:51:45.026410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd52bdf21581d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_images_id', table_name='property_images')
    op.drop_table('property_images')
    op.add_column('properties', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('transactions', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('transactions', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('properties', 'images')
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='property_images_property_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='property_images_pkey')
    )
    op.create_index('ix_property_images_id', 'property_images', ['id'], unique=False)
    # ### end Alembic commands ###
