"""change Transactions

Revision ID: dbc8e5bd040c
Revises: 1fc7541dce6e
Create Date: 2025-06-09 14:41:08.843226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc8e5bd040c'
down_revision: Union[str, None] = '1fc7541dce6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'project_id')
    # ### end Alembic commands ###
