"""create duan table

Revision ID: ef4e97b0e4a8
Revises: b7703c2cbb3f
Create Date: 2025-05-13 12:20:11.834431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef4e97b0e4a8'
down_revision: Union[str, None] = 'b7703c2cbb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duan_id'), 'duan', ['id'], unique=False)
    op.create_index(op.f('ix_duan_title'), 'duan', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duan_title'), table_name='duan')
    op.drop_index(op.f('ix_duan_id'), table_name='duan')
    op.drop_table('duan')
    # ### end Alembic commands ###
